server:
  port: 29805

spring:
  main:
    allow-bean-definition-overriding: true

  jpa:
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/felix-db
    driverClassName: org.postgresql.Driver
    username: felix
    password: tuwafjkse8y67sB^5be%EB^v5e4s6gh